"""empty message

Revision ID: 516dcf7d6dc3
Revises: c8e9440ee590
Create Date: 2025-05-16 00:33:41.506804

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '516dcf7d6dc3'
down_revision: Union[str, None] = 'c8e9440ee590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'status',
                    existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', 'canceled', name='status'),
                    type_=sa.String(length=16),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'status',
                    existing_type=sa.String(length=16),
                    type_=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', 'canceled', name='status'),
                    existing_nullable=False)
    # ### end Alembic commands ###
