"""empty message

Revision ID: c8e9440ee590
Revises: 
Create Date: 2025-05-15 23:51:27.629046

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e9440ee590'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('payment_intent_id', sa.String(length=36), nullable=False))
    op.add_column('message', sa.Column('status', sa.Enum('pending', 'success', 'failed', 'canceled', name='status'),
                                       nullable=False))
    op.alter_column('message', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    nullable=False)
    op.alter_column('message', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'updated_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('message', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('message', 'status')
    op.drop_column('message', 'payment_intent_id')
    # ### end Alembic commands ###
