version: '3'
services:
  api:
    image: crpi-ka5m16o5z8ea5t9p.eu-west-1.personal.cr.aliyuncs.com/gotoiom/ai-visa-api
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
      update_config:
        order: start-first
    ports:
      - "8001:8001"
    environment:
      HOST: 0.0.0.0
      PORT: 8001
      DEBUG: 1
      WEB_SERVER_URL: http://192.168.50.24:3000
      POSTGRES_URL: postgresql+psycopg2://postgres:PG202410122130@192.168.50.24/ai-visa
      POSTGRES_ECHO: 1
      LOG_LEVEL: debug
      TEMP_FILE_PATH: ./data/tmp
      OPENAI_BASE_URL: https://az.gptplus5.com/v1
      OPENAI_API_KEY: sk-xxxx
      ASSEMBLY_API_KEY: xxxx
      STRAPI_BASE_URL: http://192.168.50.24:1339/api
      STRAPI_API_TOKEN: xxxxx
      ALIYUN_ACCESS_KEY_ID: LTAI5tLEZ2rQhV4mMD69XnVj
      ALIYUN_ACCESS_KEY_SECRET: xxxx
      ALIYUN_BUCKET_ENDPOINT: https://oss-ap-southeast-1.aliyuncs.com
      ALIYUN_BUCKET_NAME: ai-visa
      ALIYUN_BUCKET_REGION: ap-southeast-1
      OSS_DEFAULT_EXPIRES: 300
      PROXY_API_BASE_URL:
      PROXY_URL: http://mhiz63952-region-SG-sid-F2GWG1z9-t-5:xxxxxxxxxx@sg2.cliproxy.io:443
      JWT_PRIVATE_KEY: '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCb2hiBgZ8IADHT\na8Cvrt4SNa6UkXWUVqll+Nyyq//Ih1H+gLeyzCq+Bxr1iK0pXZiNqFovQUDsjGYH\nsmvISS2wEpj8I56QfCY4R9i8X5gkl9ET9eJoVpcQjWFwAlK6TN82YBz20rGV0+5L\nSX4vbtROaiIqeET5PF5tL6g5d9jgg0mVQn35iBq3K4jEUYR2fK1JzQsT6XJ8DzB5\nxUjcokug59Ky/AiT8oO5VO7Vr6yAtrzzh1k919mrbrlff4IUR+bHDPtJu7TN1JUJ\nunxzmvoeHXPvivYWxupXqGWkfqGfLrMrr4VWAQ3dNB7dcck1tubKSL88OdyJp8GJ\n1mAKcennAgMBAAECggEABDcTV5lWYESFFHdDGF1N40cxaBJBEFiBr2DaMzjkq5tB\nU/VOQpc0BryxdXeTW12NLTOi8Mk+hMdNUSL5uEqGYk82dQdPmA/LhtUmnv2k40R5\n4qTRUUoaPtfcDUf6zdAbb2CNF/3d0LQRK1cbAxRnyJElSGnFT8pasXBLB/beVkAb\n83T3Tlc1wv2cMJWbEWn0NSieME7bauk+g6wU3aJW4/RUWv+dSIbpoYUa3PZi29q3\nSOS28RGcIoLDtzi9Pa97pUNs+7CkQrifjesAs0V6cLU55ZItYXknrDSqelcaKj7N\ns01gQjhFKbPHQPb7ecxDrl7da1Cn23dkcHjU4Q0QrQKBgQDOOTejiMNF3jqHbGwo\nNoSt99AHOkQc45l9XtaZgVsp8dLi9+GD/11KMgpEG8vaaNCkzELNSmUARr+2EbOm\nLHzZc4YyCnJXX5De7myi5jEFflIhc3XEUGKac7oR3Nil98Ksqet06L294iNNj7GL\nkOwwSCAMzFdEbjvMqqQ8iebGDQKBgQDBeFzHVORNWCElbCU/gXbJywt63sQ1o1c8\nZZaT9MaonDO6LDIXXzAsiiVr0VLXCpm+YAdCr0VTIRsDTk7u+x1BpWhGqrk7cAOw\nikoT3K3zcR6kejHMXT4W7u5M/ac1vINbxt0vnA2/DOlAHiCn1KKjEDKxZmoLIINL\nnvVIkKfGwwKBgDV8taeewzcN6pRRVMQhT8xnZ/dX726mwZq4zGRIHsMES7Q+oqk/\nxIyH6g28P+VIJkV4DSN91jB6KSMp+DRzeXZU9ktoVju/N636nQarOa+5EchHUBY4\n2zpAJdSYOUDiwAVUlRNfgkcLrihhyqTuU7Q6IMXxAflnte7hm3NwOQDJAoGBAIAN\nW1MvtAAhUacEQk8bMHV1p76GjVV3LDk0gAqj240j/fS+ZdUkUq1YLlaDcJIWWRYx\nVvzjJz5TTh7NCN+SY5Xclf0X6IwXosmJbmhhCt1zRLXWjvlVyc/CCwX4aWDeyg7H\nvARUBKEsOYIPrsuGqLLG+NaEE7ITrfMyXeTOoc2jAoGAY2gVxU0MM9Bcm4Pfm8UM\ngX03ClP0o70yDeenRP0WKpjgpk2uv8sZdNtf8Q14YNeXiFSShVNH8IUnzpcrKmlU\n+bJIco4T0nUIagy/3Jf97hsriNubwtWLo1Y3F1F+5fDC7v1257PWVlU3PSWa6S1U\nHy3ssF1Jnz6loJuF7t9TNMU=\n-----END PRIVATE KEY-----\n'
      JWT_PUBLIC_KEY: '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm9oYgYGfCAAx02vAr67e\nEjWulJF1lFapZfjcsqv/yIdR/oC3sswqvgca9YitKV2YjahaL0FA7IxmB7JryEkt\nsBKY/COekHwmOEfYvF+YJJfRE/XiaFaXEI1hcAJSukzfNmAc9tKxldPuS0l+L27U\nTmoiKnhE+TxebS+oOXfY4INJlUJ9+YgatyuIxFGEdnytSc0LE+lyfA8wecVI3KJL\noOfSsvwIk/KDuVTu1a+sgLa884dZPdfZq265X3+CFEfmxwz7Sbu0zdSVCbp8c5r6\nHh1z74r2FsbqV6hlpH6hny6zK6+FVgEN3TQe3XHJNbbmyki/PDnciafBidZgCnHp\n5wIDAQAB\n-----END PUBLIC KEY-----'
      ACCESS_TOKEN_EXPIRE_MINUTES: 21600
      SMTP_SERVER: smtp.feishu.cn
      SMTP_PORT: 587
      SMTP_USER: no-reply@anyconverters.com
      SMTP_PASSWORD: xxxx