version: "3"
services:
  web:
    image: crpi-ka5m16o5z8ea5t9p.eu-west-1.personal.cr.aliyuncs.com/gotoiom/ai-visa-web
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      update_config:
        order: start-first
    ports:
      - "3002:3002"
    environment:
      HOST: 0.0.0.0
      PORT: 3002
      NEXT_PUBLIC_BASE_URL: http://localhost:3002
      STRIPE_BASE_URL: https://api.stripe.com
      STRIPE_SECRET_KEY: sk_texxxxxx
      NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_xxxxx
      AUTH_SECRET: DtRKjJoWsiTb9L~Hw0tDGz*%@kFVKvN!Z-UxHpr9hq}.~ZfqfpX]-L!%:v)ZtQ,i^u9rxx?xE66xQR
      STRAPI_API_TOKEN: xxxxx
      NEXT_PUBLIC_PAGE_LIMIT: 5
      STRAPI_FORM_SUBMISSION_TOKEN: your-form-submission-token
      NEXT_PUBLIC_STRAPI_API_URL: http://192.168.50.24:1339
      STRAPI_API_URL: http://192.168.50.24:1339
      AI_VISA_API_BASE_URL: http://192.168.50.24:8001/ai-visa/api/v1